### ISSUE TITLE
The Get method throws an exception on optional member parse

### ISSUE THREAD

**Issue by ZarkariaDia** [vostok/configuration#23]
GetSettings() throws `SettingsBindingException` with `Value cannot be parsed` message:

``` CSharp
public class Settings
{
  [Vostok.Configuration.Abstractions.Attributes.Optional]
  public int A = 1;
}

public Settings GetSettings()
{
  var configProvider = new ConfigurationProvider();
  var source = new JsonStringSource("{ \"A\": \"abacaba\"}");
  configProvider.SetupSourceFor<Settings>(source);
  return configProvider.Get<Settings>();
}
```

**Comment by iloktionov** [comment]
After much consideration I've decided to keep current behaviour and correct the description of `OptionalAttribute` instead. Here are the main reasons for it:
- Everything is optional by default. Without parse errors, it would be possible to mess up the entire config and never notice.
- Incorrect value format is an issue that always indicates a bug/problem and is thus worth investigating.
- We already have a form of protection from sudden incorrect config changes with caching (config provider won't throw any errors once it has seen a correct config). Masking the problems at startup looks detrimental to me, though, due to the previous point.
